### ISSUE TITLE
Button Tooltips won't work in IE9

### ISSUE THREAD

**Issue by bernd-s** [egoist/data-tip.css#1]
Hi,

the tooltips which are set on buttons in your example don't work in IE9. Is this wrong in the example page, or just not possible in IE9?

Example Page: https://egoist.github.io/data-tip.css/

Regards
Bernd

**Comment by egoist** [comment]
can u give me a screenshot of how it looks like under ie9?

**Comment by bernd-s** [comment]
Here are three Screenshots, although you don't see the mouse it is hovering over the respective elements. Does that help?

![Mouse over buttons (no tooltip)](https://cloud.githubusercontent.com/assets/7986181/10536901/d0c23336-73ee-11e5-92b3-b64401523cbb.png)
![Mouse over text (tooltip works)](https://cloud.githubusercontent.com/assets/7986181/10536900/d0c2242c-73ee-11e5-99bf-06d323fa891f.png)
![Mouse over colored buttons (no tooltip)](https://cloud.githubusercontent.com/assets/7986181/10536899/d0bede16-73ee-11e5-87dd-78c43eb3c95a.png)

**Comment by bernd-s** [comment]
This was tested with the modern IE Virtual machine, which can be obtained here:
https://dev.modern.ie

Downloads of Virtual machines: https://dev.modern.ie/tools/vms/

**Comment by egoist** [comment]
maybe add a `overflow: visible;` to that button would work, I'll test it later.

**Comment by egoist** [comment]
thanks for the well detailed issue, adding `overflow: visibile;` solves this problem, however the transition effect would never work on ie9 with pure css.
