### ISSUE TITLE
窄屏超出边界

### ISSUE THREAD

**Issue by Aqours** [egoist/data-tip.css#2]
窄屏的情况下，在左右显示的时候会出现横向滚动条，然而此时data-tip内容如果被遮住的话就没什么用了。

**Comment by egoist** [comment]
如果这种情况很常见就只能尽量选择 `top` `bottom` 了，毕竟纯 CSS 似乎无法解决。

**Comment by egoist** [comment]
233 我发现 http://kushagragour.in/lab/hint/ 现在支持 arrow 居中显示了。
